# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BingoPhotoViewerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BingoPhotoViewerDemo
  pod 'Kingfisher'
  target 'BingoPhotoViewerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BingoPhotoViewerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
